### ISSUE TITLE
2016-12-12 (一） 需要完成的內容

### ISSUE THREAD

**Issue by Jiaching** [InstanBang/InstanBang#1]
# 2016-11-28 (一）

- [x] #2 - @jiaching
- [x] #3 - @slashpot 
- [ ] #4 - @lyj04061525 
- [ ] #5 - @gary1346aa 

以及每個人留言寫下自己找到的職業和asset
  - https://www.assetstore.unity3d.com/en/#!/content/61548
  - https://www.assetstore.unity3d.com/en/#!/content/49955
  - https://www.assetstore.unity3d.com/en/#!/content/47735（候補）

# 2016-12-05 (一）
請寫下每個禮拜需要完成的內容

- [x] #13 - @jiaching
- [x]  #14 - @slashpot 
- [ ] #4 - @lyj04061525 
- [ ] #5  - @gary1346aa 

# 2016-12-12 (一）
- [x] #4 - @lyj04061525 
- [ ] #5  - @gary1346aa 
- [x] #22  - @jiaching
- [x] #23 - @jiaching

**Comment by Jiaching** [comment]
請寫下每個禮拜需要完成的內容

- [x] #2 - @jiaching
- [x] #3 - @slashpot 
- [ ] #4 - @lyj04061525 
- [ ] #5 

以及每個人留言寫下自己找到的職業和asset

**Comment by lyj04061525** [comment]
https://www.assetstore.unity3d.com/en/#!/content/27670 機器
